namespace FFmpeg.AutoGen.Interop
{
    public enum AVAudioServiceType
    {
        AV_AUDIO_SERVICE_TYPE_MAIN,
        AV_AUDIO_SERVICE_TYPE_EFFECTS,
        AV_AUDIO_SERVICE_TYPE_VISUALLY_IMPAIRED,
        AV_AUDIO_SERVICE_TYPE_HEARING_IMPAIRED,
        AV_AUDIO_SERVICE_TYPE_DIALOGUE,
        AV_AUDIO_SERVICE_TYPE_COMMENTARY,
        AV_AUDIO_SERVICE_TYPE_EMERGENCY,
        AV_AUDIO_SERVICE_TYPE_VOICE_OVER,
        AV_AUDIO_SERVICE_TYPE_KARAOKE,
        AV_AUDIO_SERVICE_TYPE_NB,
    }
}